name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Observium Image build
      run: docker build . --file Dockerfile --tag ghcr.io/tathar26/observium:latest
    - name: publish container
      run: docker push ghcr.io/tathar26/observium:latest
